# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clamav.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clamav.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lamav.proto\x12\x06\x63lamav\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x0fScanFileRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"E\n\x11ScanStreamRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\"T\n\x0cScanResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tscan_time\x18\x03 \x01(\x01\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t2\x98\x02\n\rClamAVScanner\x12\x46\n\x0bHealthCheck\x12\x1a.clamav.HealthCheckRequest\x1a\x1b.clamav.HealthCheckResponse\x12\x39\n\x08ScanFile\x12\x17.clamav.ScanFileRequest\x1a\x14.clamav.ScanResponse\x12?\n\nScanStream\x12\x19.clamav.ScanStreamRequest\x1a\x14.clamav.ScanResponse(\x01\x12\x43\n\x0cScanMultiple\x12\x19.clamav.ScanStreamRequest\x1a\x14.clamav.ScanResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clamav_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=24
  _globals['_HEALTHCHECKREQUEST']._serialized_end=44
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=46
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=100
  _globals['_SCANFILEREQUEST']._serialized_start=102
  _globals['_SCANFILEREQUEST']._serialized_end=151
  _globals['_SCANSTREAMREQUEST']._serialized_start=153
  _globals['_SCANSTREAMREQUEST']._serialized_end=222
  _globals['_SCANRESPONSE']._serialized_start=224
  _globals['_SCANRESPONSE']._serialized_end=308
  _globals['_CLAMAVSCANNER']._serialized_start=311
  _globals['_CLAMAVSCANNER']._serialized_end=591
# @@protoc_insertion_point(module_scope)
