# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clamav_sdk._proto import clamav_pb2 as clamav__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clamav_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClamAVScannerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/clamav.ClamAVScanner/HealthCheck',
                request_serializer=clamav__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=clamav__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ScanFile = channel.unary_unary(
                '/clamav.ClamAVScanner/ScanFile',
                request_serializer=clamav__pb2.ScanFileRequest.SerializeToString,
                response_deserializer=clamav__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ScanStream = channel.stream_unary(
                '/clamav.ClamAVScanner/ScanStream',
                request_serializer=clamav__pb2.ScanStreamRequest.SerializeToString,
                response_deserializer=clamav__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ScanMultiple = channel.stream_stream(
                '/clamav.ClamAVScanner/ScanMultiple',
                request_serializer=clamav__pb2.ScanStreamRequest.SerializeToString,
                response_deserializer=clamav__pb2.ScanResponse.FromString,
                _registered_method=True)


class ClamAVScannerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanMultiple(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClamAVScannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=clamav__pb2.HealthCheckRequest.FromString,
                    response_serializer=clamav__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ScanFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanFile,
                    request_deserializer=clamav__pb2.ScanFileRequest.FromString,
                    response_serializer=clamav__pb2.ScanResponse.SerializeToString,
            ),
            'ScanStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ScanStream,
                    request_deserializer=clamav__pb2.ScanStreamRequest.FromString,
                    response_serializer=clamav__pb2.ScanResponse.SerializeToString,
            ),
            'ScanMultiple': grpc.stream_stream_rpc_method_handler(
                    servicer.ScanMultiple,
                    request_deserializer=clamav__pb2.ScanStreamRequest.FromString,
                    response_serializer=clamav__pb2.ScanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clamav.ClamAVScanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clamav.ClamAVScanner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClamAVScanner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clamav.ClamAVScanner/HealthCheck',
            clamav__pb2.HealthCheckRequest.SerializeToString,
            clamav__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clamav.ClamAVScanner/ScanFile',
            clamav__pb2.ScanFileRequest.SerializeToString,
            clamav__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/clamav.ClamAVScanner/ScanStream',
            clamav__pb2.ScanStreamRequest.SerializeToString,
            clamav__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanMultiple(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/clamav.ClamAVScanner/ScanMultiple',
            clamav__pb2.ScanStreamRequest.SerializeToString,
            clamav__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
